# Generated by Django 5.2 on 2025-04-11 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivovanyObjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('dokument', 'Dokument'), ('fotografie', 'Fotografie')], max_length=20)),
                ('datum_archivace', models.DateField()),
                ('popis', models.TextField(blank=True)),
                ('stari', models.IntegerField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Druh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('narozeni', models.DateField(blank=True, null=True)),
                ('umrti', models.DateField(blank=True, null=True)),
                ('pohlavi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Soubor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='archivovane_soubory/')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografie',
            fields=[
                ('archivovanyobjekt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archiv_app.archivovanyobjekt')),
                ('typ_fotografie', models.CharField(max_length=50)),
                ('vyska', models.PositiveIntegerField()),
                ('sirka', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Fotografie',
                'verbose_name_plural': 'Fotografie',
            },
            bases=('archiv_app.archivovanyobjekt',),
        ),
        migrations.AddField(
            model_name='archivovanyobjekt',
            name='osoba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archiv_app.osoba'),
        ),
        migrations.AddField(
            model_name='archivovanyobjekt',
            name='osoby',
            field=models.ManyToManyField(blank=True, related_name='objekty', to='archiv_app.osoba'),
        ),
        migrations.AddField(
            model_name='archivovanyobjekt',
            name='soubor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archiv_app.soubor'),
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('archivovanyobjekt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archiv_app.archivovanyobjekt')),
                ('jazyk', models.CharField(max_length=50)),
                ('druh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archiv_app.druh')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumenty',
            },
            bases=('archiv_app.archivovanyobjekt',),
        ),
    ]
