# Generated by Django 5.2 on 2025-05-09 07:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivovanyobjekt',
            options={'ordering': ['-datum_archivace', 'typ'], 'verbose_name': 'Archivovaný objekt', 'verbose_name_plural': 'Archivované objekty'},
        ),
        migrations.AlterModelOptions(
            name='dokument',
            options={'ordering': ['-datum_archivace', 'jazyk'], 'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumenty'},
        ),
        migrations.AlterModelOptions(
            name='druh',
            options={'ordering': ['nazev'], 'verbose_name': 'Druh dokumentu', 'verbose_name_plural': 'Druhy dokumentů'},
        ),
        migrations.AlterModelOptions(
            name='fotografie',
            options={'ordering': ['-datum_archivace', 'typ_fotografie'], 'verbose_name': 'Fotografie', 'verbose_name_plural': 'Fotografie'},
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['prijmeni', 'jmeno'], 'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterModelOptions(
            name='soubor',
            options={'verbose_name': 'Soubor', 'verbose_name_plural': 'Soubory'},
        ),
        migrations.AlterField(
            model_name='archivovanyobjekt',
            name='datum_archivace',
            field=models.DateField(default=django.utils.timezone.now, help_text='Datum archivace objektu', verbose_name='Datum archivace'),
        ),
        migrations.AlterField(
            model_name='archivovanyobjekt',
            name='osoba',
            field=models.ForeignKey(blank=True, help_text='Osoba, s objektem spojená', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archiv_app.osoba', verbose_name='Osoba'),
        ),
        migrations.AlterField(
            model_name='archivovanyobjekt',
            name='osoby',
            field=models.ManyToManyField(blank=True, help_text='Osoby spojené s objektem', related_name='objekty', to='archiv_app.osoba', verbose_name='Osoby'),
        ),
        migrations.AlterField(
            model_name='archivovanyobjekt',
            name='popis',
            field=models.TextField(blank=True, help_text='Popis objektu', verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='archivovanyobjekt',
            name='soubor',
            field=models.ForeignKey(blank=True, help_text='Soubor k archivaci', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archiv_app.soubor', verbose_name='Soubor'),
        ),
        migrations.AlterField(
            model_name='archivovanyobjekt',
            name='stari',
            field=models.IntegerField(help_text='Z jakého roku objekt pochází', verbose_name='Stáří'),
        ),
        migrations.AlterField(
            model_name='archivovanyobjekt',
            name='typ',
            field=models.CharField(choices=[('dokument', 'Dokument'), ('fotografie', 'Fotografie')], help_text='Typ objektu', max_length=20, verbose_name='Typ objektu'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='druh',
            field=models.ForeignKey(blank=True, help_text='Vyberte druh dokumentu.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archiv_app.druh', verbose_name='Druh dokumentu'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='jazyk',
            field=models.CharField(choices=[('cs', 'Čeština'), ('sk', 'Slovenština'), ('en', 'Angličtina'), ('de', 'Němčina'), ('pl', 'Polština'), ('fr', 'Francouzština'), ('la', 'Latina'), ('ru', 'Ruština'), ('jin', 'Jiný')], default='cs', error_messages={'blank': 'Jazyk dokumentu musí být vybrán.'}, help_text='Vyberte jazyk, ve kterém je dokument napsán.', max_length=3, verbose_name='Jazyk dokumentu'),
        ),
        migrations.AlterField(
            model_name='druh',
            name='nazev',
            field=models.CharField(help_text='Název druhu dokumentu', max_length=100, verbose_name='Název druhu'),
        ),
        migrations.AlterField(
            model_name='druh',
            name='popis',
            field=models.TextField(blank=True, help_text='Popis druhu dokumentu', verbose_name='Popis druhu'),
        ),
        migrations.AlterField(
            model_name='fotografie',
            name='sirka',
            field=models.PositiveIntegerField(error_messages={'blank': 'Šířka fotografie musí být vyplněna.'}, help_text='Zadejte šířku fotografie (musí být > 0).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Šířka (cm)'),
        ),
        migrations.AlterField(
            model_name='fotografie',
            name='typ_fotografie',
            field=models.CharField(blank=True, help_text='Např. portrét, krajina, reportážní, skupinová.', max_length=50, verbose_name='Typ fotografie'),
        ),
        migrations.AlterField(
            model_name='fotografie',
            name='vyska',
            field=models.PositiveIntegerField(error_messages={'blank': 'Výška fotografie musí být vyplněna.'}, help_text='Zadejte výšku fotografie (musí být > 0).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Výška (cm)'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='jmeno',
            field=models.CharField(help_text='Jméno osoby', max_length=100, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='narozeni',
            field=models.DateField(blank=True, help_text='Datum narození osoby', null=True, verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='pohlavi',
            field=models.CharField(blank=True, choices=[('M', 'Muž'), ('F', 'Žena')], help_text='Pohlaví osoby', max_length=10, null=True, verbose_name='Pohlaví'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='prijmeni',
            field=models.CharField(help_text='Příjmení osoby', max_length=100, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='umrti',
            field=models.DateField(blank=True, help_text='Datum úmrtí osoby', null=True, verbose_name='Datum úmrtí'),
        ),
        migrations.AlterField(
            model_name='soubor',
            name='file',
            field=models.FileField(help_text='Soubor k archivaci', upload_to='archivovane_soubory/', verbose_name='Soubor'),
        ),
    ]
