# Generated by Django 5.2 on 2025-05-29 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv_app', '0002_alter_archivovanyobjekt_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivovanyobjekt',
            name='stari',
        ),
        migrations.AddField(
            model_name='archivovanyobjekt',
            name='datum_vzniku_presne',
            field=models.DateField(blank=True, help_text='Přesné datum vzniku objektu (DD.MM.RRRR).', null=True, verbose_name='Přesné datum vzniku'),
        ),
        migrations.AddField(
            model_name='archivovanyobjekt',
            name='rok_vzniku',
            field=models.PositiveIntegerField(blank=True, help_text='Rok vzniku objektu (např. 1950).', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2030)], verbose_name='Rok vzniku'),
        ),
        migrations.AddField(
            model_name='archivovanyobjekt',
            name='stoleti_vzniku',
            field=models.CharField(blank=True, choices=[('15', '15. století'), ('16', '16. století'), ('17', '17. století'), ('18', '18. století'), ('19', '19. století'), ('20', '20. století'), ('21', '21. století')], help_text='Století, ve kterém objekt vznikl.', max_length=2, null=True, verbose_name='Století vzniku'),
        ),
        migrations.AlterField(
            model_name='archivovanyobjekt',
            name='typ',
            field=models.CharField(choices=[('dokument', 'Dokument'), ('fotografie', 'Fotografie')], error_messages={'blank': 'Typ objektu musí být vybrán.'}, help_text='Typ objektu', max_length=20, verbose_name='Typ objektu'),
        ),
        migrations.AlterField(
            model_name='druh',
            name='nazev',
            field=models.CharField(error_messages={'blank': 'Název druhu dokumentu nesmí být prázdný.'}, help_text='Název druhu dokumentu', max_length=100, verbose_name='Název druhu'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='jmeno',
            field=models.CharField(error_messages={'blank': 'Jméno osoby nesmí být prázdné.'}, help_text='Jméno osoby', max_length=100, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='prijmeni',
            field=models.CharField(error_messages={'blank': 'Příjmení osoby nesmí být prázdné.'}, help_text='Příjmení osoby', max_length=100, verbose_name='Příjmení'),
        ),
    ]
