# Generated by Django 5.2 on 2025-05-30 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv_app', '0003_remove_archivovanyobjekt_stari_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivovanyobjekt',
            name='soubor',
            field=models.ForeignKey(blank=True, help_text='Soubor k archivaci', null=True, on_delete=django.db.models.deletion.CASCADE, to='archiv_app.soubor', verbose_name='Soubor'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='pohlavi',
            field=models.CharField(blank=True, choices=[('M', 'Muž'), ('F', 'Žena')], help_text='Pohlaví osoby', max_length=1, null=True, verbose_name='Pohlaví'),
        ),
    ]
